name: "H. Gabriel Hern치ndez-Le칩n"                                 
output_dir: "."
navbar:
  title: "H. Gabriel Hern치ndez-Le칩n"                             
  type: inverse
  left:
    - text: "Home"
      icon: fa-home
      href: index.md
    - text: "About"
      icon: fa-user 
      href: about.md
  right:
    - text: "Contact me"
      icon: fa-envelope-o
      href: mailto:hector.hernandezl@outlook.es
    - text: "GitHub"
      icon: fa-github
      href: https://github.com/gabriel-hdezleon
output:
  html_document:
    theme: cosmo
    highlight: textmate
